language: python
python:
  - '3.9'

env:
  - INGNAME=flask-example_web

services:
  - docker

install:
  - pip install tox-travis

script:
  - tox

deploy:
  skip_cleanup: true
  provider: script
  script: ./deploy.sh
  on:
    branch: main
