language: python
python:
  - '3.9'

env:
  - IMAGE_NAME=zxcv198/flask-example:1.0.2

services:
  - docker

install:
  - pip install tox-travis

script:
  - tox

deploy:
  skip_cleanup: true
  provider: script
  script: chmod +x ./deploy-k8s.sh && ./deploy-k8s.sh
  on:
    branch: main
