version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /web
    ports:
      - "8081:5000"
    command:
      - sh
      - -c
      - |
        gunicorn -c gunicorn.conf.py app:app
    restart: always


    networks:
      docker-network:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

networks:
  docker-network:
    driver: bridge

volumes:
  docker-volume:
