version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: python-service
    image: zxcv198/flask-example:1.0.5
    working_dir: /web
    ports:
      - "5000:5000"
    restart: always

    networks:
      docker-network:
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

networks:
  docker-network:
    driver: bridge

volumes:
  docker-volume:
